### ISSUE TITLE
Tensor for argument #2 'mat1' is on CPU, but expected it to be on GPU (while checking arguments for addmm)

### ISSUE THREAD

**Issue by superran1** [Misaliet/Seamless-Satellite-image-Synthesis#1]
When I use Django and want to be able to display it on the web. I got the following error, I am a novice, I don't know which file is wrong, can you help me?
![image](https://user-images.githubusercontent.com/53592722/142965460-dcfd604d-d7df-46a1-bcb7-18d6dcea4f22.png)

**Comment by superran1** [comment]
> When I use Django and want to be able to display it on the web. I got the following error, I am a novice, I don't know which file is wrong, can you help me? ![image](https://user-images.githubusercontent.com/53592722/142965460-dcfd604d-d7df-46a1-bcb7-18d6dcea4f22.png)

The type of the tensor z_sample in view.py is CPU, and the tensor must be changed to GPU `z_sample= z_sample.cuda()`

**Comment by Misaliet** [comment]
Sorry I just saw your message.
This is indeed my negligence. I will fix this today.
Because of covid-19, I could not go to my office and use my office desktop which includes a GPU in the past few months, so I test these codes by my own laptop at the last time.
There may be other bugs in this code. If you encounter other problems, you can continue to submit issues.
