### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: './datasets/8k/mask/T.png'

### ISSUE THREAD

**Issue by anupamtripathi7** [Misaliet/Seamless-Satellite-image-Synthesis#2]
The repo contains no folder named 'Modified_BicycleGAN', which is used in the scripts to create seamless images. If i change the name for it from Modified_BicycleGAN to BicycleGAN, I get the following error:

`FileNotFoundError: [Errno 2] No such file or directory: './datasets/8k/mask/T.png'`

This seems to be because no folder named mask was generated by any of the files that were run before this from the script.

**Comment by Misaliet** [comment]
Sorry for the late reply.
There are indeed some errors in the SSS script (I'll fix later). Including what you said that the Modified_BicycleGAN should be changed to BicycleGAN.
The other error is because there is no input dataset. To generate large satellite image of different resolutions, maps of different resolutions are required as input. I wanted to provide some prebuilt maps earlier, but I didn't to this due to they were too big to be uploaded to GitHub and the legality of copyright of the data from Digimap being directly disclosed.
A more appropriate approach is to render the required input map from gml, dwg, ... format data downloaded from Digimap (this data is very easy to obtain as long as you are in a university.) yourself. I will update the specific steps later when I have time.
